### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by iamsyq** [cryzed/Amby#5]
Getting this Error while connecting to the Bridge
```
Traceback (most recent call last):
  File "/usr/local/bin/amby", line 11, in <module>
    load_entry_point('Amby==1.3', 'console_scripts', 'amby')()
  File "/home/mo/.local/lib/python3.7/site-packages/amby/cli.py", line 120, in main
    argument_parser.exit(main_(arguments))
  File "/home/mo/.local/lib/python3.7/site-packages/amby/cli.py", line 78, in main_
    state = bridge.lights[light]()['state']
  File "/home/mo/.local/lib/python3.7/site-packages/qhue/qhue.py", line 56, in __call__
    raise QhueException("\n".join(errors))
qhue.qhue.QhueException: resource, /lights/1, not available

```

**Comment by jcklpe** [comment]
@iamsyq  were you able to fix this?
